BEGIN;

-- Normalize invalid textual nulls before enforcing canonical lote links.
UPDATE public.rebanho
SET
  "loteID" = NULL,
  "loteNome" = NULL
WHERE lower(btrim(COALESCE("loteID", ''))) = 'null'
   OR lower(btrim(COALESCE("loteNome", ''))) = 'null';

-- Resolve legacy rows where loteID contains a unique lote name.
WITH nomes_unicos AS (
  SELECT id_propriedade, nome, min(id_lote) AS id_lote
  FROM public.lotes
  WHERE COALESCE(deletado, 'NAO') = 'NAO'
    AND NULLIF(btrim(nome), '') IS NOT NULL
    AND NULLIF(btrim(id_lote), '') IS NOT NULL
  GROUP BY id_propriedade, nome
  HAVING count(*) = 1
)
UPDATE public.rebanho r
SET
  "loteID" = n.id_lote,
  "loteNome" = n.nome
FROM nomes_unicos n
WHERE r."idPropriedade" = n.id_propriedade
  AND lower(btrim(COALESCE(r."loteID", ''))) = lower(btrim(n.nome))
  AND NOT EXISTS (
    SELECT 1
    FROM public.lotes exact_lote
    WHERE exact_lote.id_propriedade = r."idPropriedade"
      AND exact_lote.id_lote = r."loteID"
      AND COALESCE(exact_lote.deletado, 'NAO') = 'NAO'
  );

-- Invalid links cannot remain attached to an animal.
UPDATE public.rebanho r
SET
  "loteID" = NULL,
  "loteNome" = NULL
WHERE NULLIF(btrim(COALESCE(r."loteID", '')), '') IS NOT NULL
  AND lower(btrim(r."loteID")) <> 'null'
  AND NOT EXISTS (
    SELECT 1
    FROM public.lotes l
    WHERE l.id_propriedade = r."idPropriedade"
      AND l.id_lote = r."loteID"
      AND COALESCE(l.deletado, 'NAO') = 'NAO'
  );

-- loteNome is display data derived from the canonical loteID.
UPDATE public.rebanho r
SET "loteNome" = l.nome
FROM public.lotes l
WHERE l.id_propriedade = r."idPropriedade"
  AND l.id_lote = r."loteID"
  AND COALESCE(l.deletado, 'NAO') = 'NAO'
  AND r."loteNome" IS DISTINCT FROM l.nome;

CREATE OR REPLACE FUNCTION public.validar_lote_rebanho()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lote public.lotes%ROWTYPE;
BEGIN
  IF NULLIF(btrim(COALESCE(NEW."loteID", '')), '') IS NULL
     OR lower(btrim(NEW."loteID")) = 'null' THEN
    NEW."loteID" := NULL;
    NEW."loteNome" := NULL;
    RETURN NEW;
  END IF;

  SELECT l, true
  INTO v_lote
  FROM public.lotes l
  WHERE l.id_propriedade = NEW."idPropriedade"
    AND l.id_lote = btrim(NEW."loteID")
    AND COALESCE(l.deletado, 'NAO') = 'NAO'
  LIMIT 1;

  IF v_lote.id IS NULL THEN
    RAISE EXCEPTION 'Lote invalido para a propriedade do animal';
  END IF;

  NEW."loteID" := v_lote.id_lote;
  NEW."loteNome" := v_lote.nome;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_lote_rebanho ON public.rebanho;
CREATE TRIGGER trg_validar_lote_rebanho
BEFORE INSERT OR UPDATE OF "idPropriedade", "loteID"
ON public.rebanho
FOR EACH ROW
EXECUTE FUNCTION public.validar_lote_rebanho();

CREATE TABLE IF NOT EXISTS public.rebanho_lote_movimentacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_propriedade text NOT NULL,
  id_rebanho text NOT NULL,
  lote_anterior text,
  lote_novo text,
  origem text NOT NULL DEFAULT 'rebanho_update',
  usuario_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.registrar_movimentacao_lote_rebanho()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW."loteID" IS DISTINCT FROM OLD."loteID" THEN
    INSERT INTO public.rebanho_lote_movimentacoes (
      id_propriedade,
      id_rebanho,
      lote_anterior,
      lote_novo,
      origem,
      usuario_id
    ) VALUES (
      NEW."idPropriedade",
      NEW."idRebanho",
      OLD."loteID",
      NEW."loteID",
      COALESCE(NULLIF(current_setting('app.lote_origem', true), ''), 'rebanho_update'),
      NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_registrar_movimentacao_lote_rebanho ON public.rebanho;
CREATE TRIGGER trg_registrar_movimentacao_lote_rebanho
AFTER UPDATE OF "loteID" ON public.rebanho
FOR EACH ROW
EXECUTE FUNCTION public.registrar_movimentacao_lote_rebanho();

CREATE OR REPLACE FUNCTION public.sincronizar_animais_por_status_lote()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lote_vendido boolean;
BEGIN
  IF COALESCE(NEW.deletado, 'NAO') <> 'NAO'
     OR btrim(COALESCE(NEW.id_propriedade, '')) = ''
     OR btrim(COALESCE(NEW.id_lote, '')) = '' THEN
    RETURN NEW;
  END IF;

  v_lote_vendido := NEW.ativo = 'Inativo' AND NEW.motivo = 'Lote vendido';

  UPDATE public.rebanho r
  SET
    "loteNome" = NEW.nome,
    status = CASE WHEN v_lote_vendido THEN 'Vendido' ELSE 'Na propriedade' END,
    "dataVenda" = CASE WHEN v_lote_vendido THEN NEW.data_motivo ELSE NULL END,
    "valorVenda" = CASE WHEN v_lote_vendido THEN NEW."valorVenda" ELSE NULL END,
    updated_at = now()
  WHERE r."idPropriedade" = NEW.id_propriedade
    AND COALESCE(r.deletado, 'NAO') = 'NAO'
    AND r."loteID" = NEW.id_lote;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sincronizar_animais_por_status_lote ON public.lotes;
CREATE TRIGGER trg_sincronizar_animais_por_status_lote
AFTER INSERT OR UPDATE OF nome, ativo, motivo, data_motivo, "valorVenda"
ON public.lotes
FOR EACH ROW
EXECUTE FUNCTION public.sincronizar_animais_por_status_lote();

CREATE OR REPLACE FUNCTION public.salvar_lote_com_composicao(
  p_id_propriedade text DEFAULT '',
  p_id_lote text DEFAULT '',
  p_nome text DEFAULT NULL,
  p_anotacoes text DEFAULT NULL,
  p_ativo text DEFAULT 'Ativo',
  p_motivo text DEFAULT NULL,
  p_data_motivo timestamptz DEFAULT NULL,
  p_valor_venda numeric DEFAULT NULL,
  p_animais_ids text DEFAULT '[]',
  p_composicao_esperada text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lote public.lotes%ROWTYPE;
  v_animais_json jsonb := '[]'::jsonb;
  v_esperada_json jsonb := '[]'::jsonb;
  v_ids text[] := ARRAY[]::text[];
  v_ids_esperados text[] := ARRAY[]::text[];
  v_ids_atuais text[] := ARRAY[]::text[];
  v_ativo text := CASE
    WHEN lower(btrim(COALESCE(p_ativo, 'Ativo'))) IN ('ativo', 'true', '1', 'sim') THEN 'Ativo'
    ELSE 'Inativo'
  END;
  v_motivo text := NULLIF(btrim(COALESCE(p_motivo, '')), '');
  v_vendido boolean;
  v_existia boolean := false;
  v_validos integer;
  v_atualizados integer;
  v_removidos integer;
BEGIN
  IF NULLIF(btrim(COALESCE(p_id_propriedade, '')), '') IS NULL
     OR NULLIF(btrim(COALESCE(p_id_lote, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Dados obrigatorios ausentes para salvar lote';
  END IF;

  IF NOT public.usuario_tem_acesso_propriedade(p_id_propriedade) THEN
    RAISE EXCEPTION 'Usuario sem acesso a propriedade';
  END IF;

  BEGIN
    v_animais_json := COALESCE(NULLIF(btrim(COALESCE(p_animais_ids, '')), '')::jsonb, '[]'::jsonb);
    v_esperada_json := COALESCE(NULLIF(btrim(COALESCE(p_composicao_esperada, '')), '')::jsonb, '[]'::jsonb);
  EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'Composicao de animais invalida';
  END;

  IF jsonb_typeof(v_animais_json) <> 'array'
     OR jsonb_typeof(v_esperada_json) <> 'array' THEN
    RAISE EXCEPTION 'Composicao de animais deve ser um array JSON';
  END IF;

  SELECT COALESCE(array_agg(DISTINCT btrim(value) ORDER BY btrim(value)) FILTER (
    WHERE btrim(value) <> '' AND lower(btrim(value)) <> 'null'
  ), ARRAY[]::text[])
  INTO v_ids
  FROM jsonb_array_elements_text(v_animais_json) AS item(value);

  SELECT COALESCE(array_agg(DISTINCT btrim(value) ORDER BY btrim(value)) FILTER (
    WHERE btrim(value) <> '' AND lower(btrim(value)) <> 'null'
  ), ARRAY[]::text[])
  INTO v_ids_esperados
  FROM jsonb_array_elements_text(v_esperada_json) AS item(value);

  SELECT l.*
  INTO v_lote
  FROM public.lotes l
  WHERE l.id_propriedade = p_id_propriedade
    AND l.id_lote = btrim(p_id_lote)
    AND COALESCE(l.deletado, 'NAO') = 'NAO'
  FOR UPDATE;

  IF FOUND THEN
    v_existia := true;
    IF p_composicao_esperada IS NOT NULL THEN
      SELECT COALESCE(array_agg(r."idRebanho" ORDER BY r."idRebanho"), ARRAY[]::text[])
      INTO v_ids_atuais
      FROM public.rebanho r
      WHERE r."idPropriedade" = p_id_propriedade
        AND r."loteID" = v_lote.id_lote
        AND COALESCE(r.deletado, 'NAO') = 'NAO';

      IF v_ids_atuais <> v_ids_esperados THEN
        RAISE EXCEPTION 'Lote alterado por outro usuario; recarregue a composicao';
      END IF;
    END IF;
  ELSE
    INSERT INTO public.lotes (
      id_propriedade,
      nome,
      anotacoes,
      ativo,
      id_lote,
      deletado,
      motivo,
      data_motivo,
      "valorVenda"
    ) VALUES (
      p_id_propriedade,
      NULLIF(btrim(COALESCE(p_nome, '')), ''),
      p_anotacoes,
      v_ativo,
      btrim(p_id_lote),
      'NAO',
      CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE v_motivo END,
      CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE p_data_motivo END,
      CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE p_valor_venda END
    )
    RETURNING * INTO v_lote;
  END IF;

  PERFORM 1
  FROM public.rebanho r
  WHERE r."idPropriedade" = p_id_propriedade
    AND (r."loteID" = v_lote.id_lote OR r."idRebanho" = ANY(v_ids))
  FOR UPDATE;

  IF cardinality(v_ids) > 0 THEN
    SELECT count(DISTINCT r."idRebanho")
    INTO v_validos
    FROM public.rebanho r
    WHERE r."idPropriedade" = p_id_propriedade
      AND COALESCE(r.deletado, 'NAO') = 'NAO'
      AND r."idRebanho" = ANY(v_ids);

    IF v_validos <> cardinality(v_ids) THEN
      RAISE EXCEPTION 'Um ou mais animais nao pertencem a propriedade';
    END IF;
  END IF;

  v_vendido := v_ativo = 'Inativo' AND v_motivo = 'Lote vendido';

  UPDATE public.lotes
  SET
    nome = COALESCE(NULLIF(btrim(COALESCE(p_nome, '')), ''), nome),
    anotacoes = COALESCE(p_anotacoes, anotacoes),
    ativo = v_ativo,
    motivo = CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE v_motivo END,
    data_motivo = CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE p_data_motivo END,
    "valorVenda" = CASE WHEN v_ativo = 'Ativo' THEN NULL ELSE p_valor_venda END,
    updated_at = now()
  WHERE id = v_lote.id
  RETURNING * INTO v_lote;

  UPDATE public.rebanho r
  SET
    "loteID" = NULL,
    "loteNome" = NULL,
    status = 'Na propriedade',
    "dataVenda" = NULL,
    "valorVenda" = NULL,
    updated_at = now()
  WHERE r."idPropriedade" = p_id_propriedade
    AND COALESCE(r.deletado, 'NAO') = 'NAO'
    AND r."loteID" = v_lote.id_lote
    AND NOT (r."idRebanho" = ANY(v_ids));
  GET DIAGNOSTICS v_removidos = ROW_COUNT;

  UPDATE public.rebanho r
  SET
    "loteID" = v_lote.id_lote,
    "loteNome" = v_lote.nome,
    status = CASE WHEN v_vendido THEN 'Vendido' ELSE 'Na propriedade' END,
    "dataVenda" = CASE WHEN v_vendido THEN v_lote.data_motivo ELSE NULL END,
    "valorVenda" = CASE WHEN v_vendido THEN v_lote."valorVenda" ELSE NULL END,
    "dataEntradaLote" = CASE WHEN r."loteID" IS DISTINCT FROM v_lote.id_lote THEN CURRENT_DATE ELSE r."dataEntradaLote" END,
    updated_at = now()
  WHERE r."idPropriedade" = p_id_propriedade
    AND COALESCE(r.deletado, 'NAO') = 'NAO'
    AND r."idRebanho" = ANY(v_ids);
  GET DIAGNOSTICS v_atualizados = ROW_COUNT;

  IF v_atualizados <> cardinality(v_ids) THEN
    RAISE EXCEPTION 'Quantidade de animais vinculados diferente da solicitada';
  END IF;

  RETURN jsonb_build_object(
    'id_lote', v_lote.id_lote,
    'animais_solicitados', cardinality(v_ids),
    'animais_vinculados', v_atualizados,
    'animais_removidos', v_removidos,
    'criado', NOT v_existia
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.salvar_lote_status_e_sincronizar_animais(
  p_id_propriedade text DEFAULT '',
  p_id_lote text DEFAULT '',
  p_nome text DEFAULT NULL,
  p_anotacoes text DEFAULT NULL,
  p_ativo text DEFAULT 'Ativo',
  p_motivo text DEFAULT NULL,
  p_data_motivo timestamptz DEFAULT NULL,
  p_valor_venda numeric DEFAULT NULL,
  p_id_animais text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.salvar_lote_com_composicao(
    p_id_propriedade,
    p_id_lote,
    p_nome,
    p_anotacoes,
    p_ativo,
    p_motivo,
    p_data_motivo,
    p_valor_venda,
    COALESCE(p_id_animais, '[]'),
    NULL
  );
$$;

GRANT EXECUTE ON FUNCTION public.salvar_lote_com_composicao(text, text, text, text, text, text, timestamptz, numeric, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.salvar_lote_status_e_sincronizar_animais(text, text, text, text, text, text, timestamptz, numeric, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
COMMIT;
